---
- name: Install and configure DHCP server
  hosts: local
  become: yes
  vars_files: vars.yml
  tasks:
    - name: Install DHCP,HTTP and TFTP packages
      yum:
        name: "{{ packages }}" 
        state: present

    - name: Copy DHCP configuration file
      template:
        src: dhcpd.conf.j2
        dest: /etc/dhcp/dhcpd.conf
        mode: 0644

    - name: Enable and start DHCP service
      service:
        name: dhcpd 
        enabled: yes
        state: started

    - name: Enable and start httpd service
      service:
        name: httpd
        enabled: yes
        state: started

    - name: Enable and start tftp service
      service:
        name: tftp
        enabled: yes
        state: started

    - name: Mount rhel9.2 iso to /mnt
      ansible.posix.mount:
        src: /dev/sr0
        path: /mnt
        fstype: iso9660
        opts: loop,ro
        state: mounted

    - name: Create /rhel-9.2 directory to copy tftpboot 
      file:
        path: /rhel-9.2
        state: directory

    - name: Copy tftpboot file to /rhel-9.2
      copy:
        src: /mnt/AppStream/Packages/syslinux-tftpboot-6.04-0.20.el9.noarch.rpm
        dest: /rhel-9.2/
        mode: "0644"

    - name: Extract rpm package
      command: sh -c "rpm2cpio /rhel-9.2/syslinux-tftpboot-6.04-0.20.el9.noarch.rpm | cpio -idmv -D /rhel-9.2/"

    - name: Unmount /mnt
      ansible.posix.mount:
        path: /mnt
        state: unmounted

    - name: Create /mnt/rhel-9.2 directory 
      file:
        path: /mnt/rhel-9.2
        state: directory

    - name: Mount rhel9.2 iso to /mnt/rhel-9.2
      ansible.posix.mount:
        src: /dev/sr0
        path: /mnt/rhel-9.2
        fstype: iso9660
        opts: loop,ro
        state: mounted

        # - name: Copy /mnt/rhel-9.2 to /var/www/html/
        #   command:
        #     cmd: "cp -r /mnt/rhel-9.2 /var/www/html/"

    
    - name: Unmount /mnt
      ansible.posix.mount:
        path: /mnt/rhel-9.2
        state: unmounted

    - name: Create rhel-9.2 Local Repo
      template:
        src: rhel_http_repo.repo.j2

    - name: Set SELinux file type for /var/lib/tftpboot(/.*)?
      sefcontext:
        target: '/var/lib/tftpboot(/.*)?'
        setype: tftpdir_rw_t
        state: present
      notify: restorecon
        dest: /etc/yum.repos.d/rhel_http_repo.repo 

    - name: Create /var/lib/tftpboot/images
      file:
        path: /var/lib/tftpboot/images
        state: directory
        setype: tftpdir_rw_t
        seuser: system_u
        serole: object_r
      notify: restorecon

    - name: Copy /var/www/html/rhel-9.2/images/pxeboot/vmlinuz
      copy:
        src: /var/www/html/rhel-9.2/images/pxeboot/vmlinuz
        dest: /var/lib/tftpboot/images

    - name: Copy /var/www/html/rhel-9.2/images/pxeboot/initrd.img
      copy:
        src: /var/www/html/rhel-9.2/images/pxeboot/initrd.img
        dest: /var/lib/tftpboot/images

    - name: Copy /rhel-9.2/tftpboot/* to /var/lib/tftpboot/
      copy:
        src: /rhel-9.2/tftpboot/*
        dest: /var/lib/tftpboot/

    - name: Create /var/lib/tftpboot/pxelinux.cfg
      file:
        path: /var/lib/tftpboot/pxelinux.cfg
        state: directory
        setype: tftpdir_rw_t
        seuser: system_u
        serole: object_r
      notify: restorecon

    - name: Copy default.j2 to /var/lib/tftpboot/pxelinux.cfg/
      template:
        src: default.j2
        dest: /var/lib/tftpboot/pxelinux.cfg/default

    - name: Create /var/www/html/ks for kickstart
      file:
        path: /var/www/html/ks
        state: directory

    - name: Copy rhel-9.2-ks.cfg.j2 
      template:
        src: rhel-9.2-ks.cfg.j2
        dest: /var/www/html/ks/rhel-9.2-ks.cfg 

    - name: Enable for tftp_home_dir 
      command:
        cmd: setsebool -P tftp_home_dir 1
    
    - name: Open firewall for HTTP
      firewalld:
        service: http
        permanent: yes
        state: enabled
        zone: public

    - name: Open firewall for dhcp
      firewalld:
        service: dhcp
        permanent: yes
        state: enabled
        zone: public

    - name: Open firewall for tftp
      firewalld:
        service: tftp
        permanent: yes
        state: enabled
        zone: public
      notify: reload firewalld
      
  handlers:
    - name: reload firewalld
      command: firewall-cmd --reload

    - name: restorecon
      command: /sbin/restorecon -R /var/lib/tftpboot
