---
- name: Configure DNS client
  hosts: dns_client
  become: yes
  tasks:
    - name: Backup the current resolv.conf
      copy:
        src: /etc/resolv.conf
        dest: /etc/resolv.conf.backup
        backup: yes

    - name: Configure /etc/resolv.conf
      template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: '0644'

    - name: Ensure NTP package is installed (for Debian/Ubuntu)
      apt:
        name: ntp
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - name: Ensure NTP package is installed (for RHEL/CentOS)
      yum:
        name: chrony
        state: present
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Configure /etc/chrony.conf
      template:
        src: chrony_client.conf.j2
        dest: /etc/chrony.conf
        owner: root
        group: root
        mode: '0644'

    - name: Ensure NTP service is enabled and started (for Debian/Ubuntu)
      service:
        name: chronyd
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == 'Debian'

    - name: Ensure NTP service is enabled and started (for RHEL/CentOS)
      service:
        name: chronyd
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == 'RedHat'