---
- name: Install and configure BIND DNS server
  hosts: all
  become: yes
  vars_files: vars.yml
  tasks:
    - name: Install bind and bind-utils package
      yum:
        name: "{{ packages }}"
        state: present

    - name: Ensure named service is enabled and started
      service:
        name: named
        state: started
        enabled: yes

    - name: Ensure NTP service is enabled and started
      systemd:
        name: chronyd
        state: started
        enabled: yes

    - name: Copy named.conf template
      template:
        src: templates/named.conf.j2
        dest: /etc/named.conf
        owner: root
        group: named
        mode: 0640

    - name: Copy linuxlab.lan.db.j2 template
      template:
        src: templates/linuxlab.lan.db.j2
        dest: /var/named/linuxlab.lan.db
        owner: root
        group: named
        mode: 0640

    - name: Copy linuxlab.lan.rev.j2 template
      template:
        src: templates/linuxlab.lan.rev.j2
        dest: /var/named/linuxlab.lan.rev
        owner: root
        group: named
        mode: 0640
      notify: restart named service

    - name: copy chrony.conf to chrony.conf.ori
      copy:
        src: /etc/chrony.conf
        dest: /etc/chrony.conf.ori
        remote_src: true
  
    - name: remove chrony.conf
      file:
        path: /etc/chrony.conf
        state: absent

    - name: Copy chrony.conf template
      template:
        src: templates/chrony.conf.j2
        dest: /etc/chrony.conf
        owner: root
        group: root
        mode: 0640
        
    - name: add name server ip /etc/resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        regexp: '^nameserver'
        line: "nameserver 192.168.124.200"

    - name: Allow DNS service in firewalld
      firewalld:
        service: dns
        zone: public
        permanent: true
        state: enabled
        
    - name: Allow NTP service in firewalld
      firewalld:
        service: ntp
        zone: public
        permanent: true
        state: enabled

    - name: Reload firewalld to apply changes
      service:
        name: firewalld
        state: reloaded
       
  handlers:
    - name: restart named service
      service:
        name: 
          - named
          - chronyd
        state: restared
        

